export const FETCH_IMAGES = "FETCH_IMAGES";
export const FETCH_MAIN = "FETCH_MAIN";

export const GET_CATEGORY_IMAGES = "GET_CATEGORY_IMAGES";
export const GET_CATEGORY_IMAGES_SUCCESS = "GET_CATEGORY_IMAGES_SUCCESS";
export const GET_CATEGORY_IMAGES_ERROR = "GET_CATEGORY_IMAGES_ERROR";

export const GET_MAIN_IMAGES = "GET_MAIN_IMAGES";
export const GET_MAIN_IMAGES_SUCCESS = "GET_MAIN_IMAGES_SUCCESS";
export const GET_MAIN_IMAGES_ERROR = "GET_MAIN_IMAGES_ERROR";

export const SET_SEARCH_ITEM = "SET_SEARCH_ITEM";